import type { Planet } from "../../types/planet";

/**
 * 40-planet buffer set — a scope-flex safety net, kept SEPARATE from the
 * 5 demo-safe featured planets. REAL DATA, fetched from the NASA Exoplanet
 * Archive (pscomppars table) on 2026-09-12.
 *
 * Curated for CATEGORY DIVERSITY across 9 categories: rocky habitable-zone,
 * super-Earth, ultra-hot/lava, ordinary hot Jupiter, mini-Neptune,
 * directly-imaged, circumbinary, pulsar-planet, and scientific oddities.
 *
 * A few entries carry a ⚠️ caution note where the science is unusually
 * contested or nuanced — read those before using them in user-facing copy.
 */

export const BUFFER_PLANETS: Planet[] = [
  {
    name: "TRAPPIST-1 d",
    radiusEarth: 0.788,
    massEarth: 0.388,
    orbitalDistanceAU: 0.02227,
    orbitalPeriodDays: 4.0492,
    orbitalEccentricity: 0.0084,
    equilibriumTemperatureK: 286.2,
    starName: "TRAPPIST-1",
    starRadiusSolar: 0.1192,
    starTemperatureK: 2566.0,
    starSpectralType: "M8.0 V",
    starMassSolar: 0.0898,
    distanceLightYears: 40.54,
    discoveryYear: 2016,
    discoveryMethod: "Transit",
    category: "rocky-habitable-zone",
    notableFact: "Innermost of the three TRAPPIST-1 planets generally considered within the habitable zone.",
  },
  {
    name: "TRAPPIST-1 f",
    radiusEarth: 1.045,
    massEarth: 1.039,
    orbitalDistanceAU: 0.03849,
    orbitalPeriodDays: 9.2075,
    orbitalEccentricity: 0.0101,
    equilibriumTemperatureK: 217.7,
    starName: "TRAPPIST-1",
    starRadiusSolar: 0.1192,
    starTemperatureK: 2566.0,
    starSpectralType: "M8.0 V",
    starMassSolar: 0.0898,
    distanceLightYears: 40.54,
    discoveryYear: 2017,
    discoveryMethod: "Transit",
    category: "rocky-habitable-zone",
    notableFact: "Outer habitable-zone TRAPPIST-1 world — pairs well with TRAPPIST-1 e to show intra-system variation.",
  },
  {
    name: "Kepler-452 b",
    radiusEarth: 1.63,
    massEarth: 3.29,
    orbitalDistanceAU: 1.046,
    orbitalPeriodDays: 384.843,
    orbitalEccentricity: 0.0,
    equilibriumTemperatureK: 265.0,
    starName: "Kepler-452",
    starRadiusSolar: 1.11,
    starTemperatureK: 5757.0,
    starSpectralType: "G2",
    starMassSolar: 1.037,
    distanceLightYears: 1799.51,
    discoveryYear: 2015,
    discoveryMethod: "Transit",
    category: "rocky-habitable-zone",
    notableFact: "Nicknamed 'Earth's cousin' — orbits a G-type (Sun-like) star, one of the few HZ candidates around a solar-type host.",
  },
  {
    name: "Kepler-22 b",
    radiusEarth: 2.1,
    massEarth: 9.1,
    orbitalDistanceAU: 0.812,
    orbitalPeriodDays: 289.8639,
    orbitalEccentricity: 0.72,
    equilibriumTemperatureK: 279.0,
    starName: "Kepler-22",
    starRadiusSolar: 0.869,
    starTemperatureK: 5596.0,
    starSpectralType: "G5 V",
    starMassSolar: 0.857,
    distanceLightYears: 634.84,
    discoveryYear: 2011,
    discoveryMethod: "Transit",
    category: "rocky-habitable-zone",
    notableFact: "First planet Kepler confirmed within the habitable zone of a Sun-like star (2011). Note: archive-listed eccentricity (0.72) is unusually high for this system — most published fits treat eccentricity as poorly constrained/near-zero; sanity-check before using in any 'stable seasons' framing.",
  },
  {
    name: "TOI-700 d",
    radiusEarth: 1.073,
    massEarth: 1.25,
    orbitalDistanceAU: 0.1633,
    orbitalPeriodDays: 37.424,
    orbitalEccentricity: 0.042,
    equilibriumTemperatureK: 268.8,
    starName: "TOI-700",
    starRadiusSolar: 0.421,
    starTemperatureK: 3459.0,
    starSpectralType: "M2.5 V",
    starMassSolar: 0.415,
    distanceLightYears: 101.52,
    discoveryYear: 2020,
    discoveryMethod: "Transit",
    category: "rocky-habitable-zone",
    notableFact: "TESS's first Earth-size habitable-zone discovery, orbiting a small cool M dwarf.",
  },
  {
    name: "LHS 1140 b",
    radiusEarth: 1.73,
    massEarth: 5.6,
    orbitalDistanceAU: 0.0946,
    orbitalPeriodDays: 24.7372,
    orbitalEccentricity: 0.043,
    equilibriumTemperatureK: 226.0,
    starName: "LHS 1140",
    starRadiusSolar: 0.2159,
    starTemperatureK: 3096.0,
    starSpectralType: "M4.5 V",
    starMassSolar: 0.1844,
    distanceLightYears: 48.88,
    discoveryYear: 2017,
    discoveryMethod: "Transit",
    category: "rocky-habitable-zone",
    notableFact: "Dense rocky super-Earth around a nearby red dwarf, considered a strong atmosphere-search target.",
  },
  {
    name: "Gliese 667 Cc",
    radiusEarth: 1.77,
    massEarth: 3.8,
    orbitalDistanceAU: 0.125,
    orbitalPeriodDays: 28.14,
    orbitalEccentricity: 0.02,
    equilibriumTemperatureK: undefined,
    starName: "Gliese 667 C",
    starRadiusSolar: undefined,
    starTemperatureK: 3350.0,
    starSpectralType: "M1.5 V",
    starMassSolar: 0.33,
    distanceLightYears: 23.63,
    discoveryYear: 2013,
    discoveryMethod: "Radial Velocity",
    category: "rocky-habitable-zone",
    notableFact: "Orbits the smallest star in a triple-star system. Archive has no equilibrium temperature or stellar radius on file for this one — good real-world test of the derive-from-spectral-type fallback.",
  },
  {
    name: "Kepler-62 f",
    radiusEarth: 1.41,
    massEarth: 35.0,
    orbitalDistanceAU: 0.718,
    orbitalPeriodDays: 267.291,
    orbitalEccentricity: 0.0,
    equilibriumTemperatureK: 208.0,
    starName: "Kepler-62",
    starRadiusSolar: 0.64,
    starTemperatureK: 4925.0,
    starSpectralType: "K2 V",
    starMassSolar: 0.69,
    distanceLightYears: 981.33,
    discoveryYear: 2013,
    discoveryMethod: "Transit",
    category: "rocky-habitable-zone",
    notableFact: "Outermost of two habitable-zone planets in the Kepler-62 system.",
  },
  {
    name: "Teegarden's Star b",
    radiusEarth: 1.05,
    massEarth: 1.16,
    orbitalDistanceAU: 0.0259,
    orbitalPeriodDays: 4.9063,
    orbitalEccentricity: 0.03,
    equilibriumTemperatureK: 277.0,
    starName: "Teegarden's Star",
    starRadiusSolar: 0.12,
    starTemperatureK: 3034.0,
    starSpectralType: "M7.0 V",
    starMassSolar: 0.097,
    distanceLightYears: 12.49,
    discoveryYear: 2019,
    discoveryMethod: "Radial Velocity",
    category: "rocky-habitable-zone",
    notableFact: "Earth-mass planet on a notably circular orbit around one of the coolest, nearest known M dwarfs.",
  },
  {
    name: "Gliese 486 b",
    radiusEarth: 1.289,
    massEarth: 2.77,
    orbitalDistanceAU: 0.01714,
    orbitalPeriodDays: 1.4671,
    orbitalEccentricity: 0.0009,
    equilibriumTemperatureK: 696.3,
    starName: "Gliese 486",
    starRadiusSolar: 0.3243,
    starTemperatureK: 3317.0,
    starSpectralType: "M3.5 V",
    starMassSolar: 0.312,
    distanceLightYears: 26.34,
    discoveryYear: 2021,
    discoveryMethod: "Radial Velocity",
    category: "super-earth",
    notableFact: "Nearby (~26 ly) hot rocky super-Earth, a prime atmosphere-detection target for JWST.",
  },
  {
    name: "LHS 3844 b",
    radiusEarth: 1.286,
    massEarth: 2.37,
    orbitalDistanceAU: 0.00624,
    orbitalPeriodDays: 0.4629,
    orbitalEccentricity: 0.0,
    equilibriumTemperatureK: 816.0,
    starName: "LHS 3844",
    starRadiusSolar: 0.189,
    starTemperatureK: 3080.0,
    starSpectralType: "M4.5-M5.0",
    starMassSolar: 0.151,
    distanceLightYears: 48.55,
    discoveryYear: 2019,
    discoveryMethod: "Transit",
    category: "super-earth",
    notableFact: "Ultra-short-period rocky world with observations suggesting little to no atmosphere — a good 'airless' showcase.",
  },
  {
    name: "HD 219134 b",
    radiusEarth: 1.602,
    massEarth: 4.74,
    orbitalDistanceAU: 0.03876,
    orbitalPeriodDays: 3.0929,
    orbitalEccentricity: 0.0,
    equilibriumTemperatureK: 1015.0,
    starName: "HD 219134",
    starRadiusSolar: 0.778,
    starTemperatureK: 4699.0,
    starSpectralType: "K3 V",
    starMassSolar: 0.81,
    distanceLightYears: 21.3,
    discoveryYear: 2015,
    discoveryMethod: "Radial Velocity",
    category: "super-earth",
    notableFact: "One of the nearest known rocky exoplanets, in a compact multi-planet system.",
  },
  {
    name: "Kepler-10 b",
    radiusEarth: 1.47,
    massEarth: 3.24,
    orbitalDistanceAU: 0.01685,
    orbitalPeriodDays: 0.8375,
    orbitalEccentricity: 0.0,
    equilibriumTemperatureK: 2188.0,
    starName: "Kepler-10",
    starRadiusSolar: 1.065,
    starTemperatureK: 5708.0,
    starSpectralType: undefined,
    starMassSolar: 0.91,
    distanceLightYears: 605.05,
    discoveryYear: 2011,
    discoveryMethod: "Transit",
    category: "ultra-hot",
    notableFact: "First confirmed rocky exoplanet found by Kepler; likely a molten-surface lava world.",
  },
  {
    name: "CoRoT-7 b",
    radiusEarth: 1.681,
    massEarth: 4.077,
    orbitalDistanceAU: 0.01702,
    orbitalPeriodDays: 0.8536,
    orbitalEccentricity: 0.0,
    equilibriumTemperatureK: 1756.0,
    starName: "CoRoT-7",
    starRadiusSolar: 0.83,
    starTemperatureK: 5275.0,
    starSpectralType: "G9 V",
    starMassSolar: 0.82,
    distanceLightYears: 521.55,
    discoveryYear: 2009,
    discoveryMethod: "Transit",
    category: "ultra-hot",
    notableFact: "First transiting rocky exoplanet ever confirmed (CoRoT mission, 2009); dayside possibly hot enough for rock vapor and 'mineral rain.'",
  },
  {
    name: "WASP-12 b",
    radiusEarth: 22.026,
    massEarth: 467.21,
    orbitalDistanceAU: 0.0234,
    orbitalPeriodDays: 1.0914,
    orbitalEccentricity: 0.0447,
    equilibriumTemperatureK: 2601.0,
    starName: "WASP-12",
    starRadiusSolar: 1.69,
    starTemperatureK: 6265.0,
    starSpectralType: undefined,
    starMassSolar: 1.325,
    distanceLightYears: 1393.51,
    discoveryYear: 2008,
    discoveryMethod: "Transit",
    category: "ultra-hot",
    notableFact: "Being tidally disrupted and slowly consumed by its host star — dramatic 'doomed planet' story.",
  },
  {
    name: "KELT-9 b",
    radiusEarth: 21.701,
    massEarth: 915.346,
    orbitalDistanceAU: 0.03368,
    orbitalPeriodDays: 1.4811,
    orbitalEccentricity: 0.0,
    equilibriumTemperatureK: 3921.0,
    starName: "KELT-9",
    starRadiusSolar: 2.418,
    starTemperatureK: 9270.0,
    starSpectralType: "A",
    starMassSolar: 2.32,
    distanceLightYears: 666.85,
    discoveryYear: 2017,
    discoveryMethod: "Transit",
    category: "ultra-hot",
    notableFact: "Hottest known exoplanet — dayside temperature rivals many stars; orbits a hot A-type star.",
  },
  {
    name: "WASP-76 b",
    radiusEarth: 20.781,
    massEarth: 284.139,
    orbitalDistanceAU: 0.033,
    orbitalPeriodDays: 1.8099,
    orbitalEccentricity: 0.0,
    equilibriumTemperatureK: 2228.0,
    starName: "WASP-76",
    starRadiusSolar: 1.756,
    starTemperatureK: 6329.0,
    starSpectralType: "F7",
    starMassSolar: 1.458,
    distanceLightYears: 634.25,
    discoveryYear: 2016,
    discoveryMethod: "Transit",
    category: "ultra-hot",
    notableFact: "'Iron rain' planet — evidence of iron vapor condensing on the cooler nightside.",
  },
  {
    name: "HD 209458 b",
    radiusEarth: 15.581,
    massEarth: 232.016,
    orbitalDistanceAU: 0.04707,
    orbitalPeriodDays: 3.5247,
    orbitalEccentricity: 0.0,
    equilibriumTemperatureK: 1459.0,
    starName: "HD 209458",
    starRadiusSolar: 1.19,
    starTemperatureK: 6091.0,
    starSpectralType: "G0 V",
    starMassSolar: 1.23,
    distanceLightYears: 157.54,
    discoveryYear: 1999,
    discoveryMethod: "Radial Velocity",
    category: "hot-jupiter",
    notableFact: "Nicknamed 'Osiris' — first exoplanet observed transiting its star, with a detected evaporating atmosphere.",
  },
  {
    name: "51 Pegasi b",
    radiusEarth: 14.1,
    massEarth: 193.875,
    orbitalDistanceAU: 0.052,
    orbitalPeriodDays: 4.2308,
    orbitalEccentricity: 0.0063,
    equilibriumTemperatureK: 1328.9,
    starName: "51 Pegasi",
    starRadiusSolar: 1.19,
    starTemperatureK: 5761.0,
    starSpectralType: "G5V",
    starMassSolar: 1.07,
    distanceLightYears: 50.43,
    discoveryYear: 1995,
    discoveryMethod: "Radial Velocity",
    category: "hot-jupiter",
    notableFact: "First exoplanet discovered orbiting a Sun-like star (1995) — the discovery that opened the field, Nobel Prize in Physics 2019.",
  },
  {
    name: "HD 189733 b",
    radiusEarth: 12.666,
    massEarth: 359.148,
    orbitalDistanceAU: 0.03126,
    orbitalPeriodDays: 2.2186,
    orbitalEccentricity: 0.0,
    equilibriumTemperatureK: 1209.0,
    starName: "HD 189733",
    starRadiusSolar: 0.75,
    starTemperatureK: 5052.0,
    starSpectralType: "K2 V",
    starMassSolar: 0.79,
    distanceLightYears: 64.46,
    discoveryYear: 2005,
    discoveryMethod: "Radial Velocity",
    category: "hot-jupiter",
    notableFact: "Famous deep-blue color from silicate haze, with winds strong enough to drive glass sideways.",
  },
  {
    name: "Kepler-7 b",
    radiusEarth: 18.181,
    massEarth: 140.163,
    orbitalDistanceAU: 0.06067,
    orbitalPeriodDays: 4.8855,
    orbitalEccentricity: 0.0,
    equilibriumTemperatureK: 1630.0,
    starName: "Kepler-7",
    starRadiusSolar: 1.966,
    starTemperatureK: 5933.0,
    starSpectralType: undefined,
    starMassSolar: 1.359,
    distanceLightYears: 3009.03,
    discoveryYear: 2009,
    discoveryMethod: "Transit",
    category: "hot-jupiter",
    notableFact: "One of the puffiest, lowest-density planets known — good extreme-low-gravity visual.",
  },
  {
    name: "WASP-17 b",
    radiusEarth: 20.961,
    massEarth: 247.907,
    orbitalDistanceAU: 0.0515,
    orbitalPeriodDays: 3.7354,
    orbitalEccentricity: 0.0,
    equilibriumTemperatureK: 1755.0,
    starName: "WASP-17",
    starRadiusSolar: 1.49,
    starTemperatureK: 6550.0,
    starSpectralType: "F4",
    starMassSolar: 2.28,
    distanceLightYears: 1323.91,
    discoveryYear: 2009,
    discoveryMethod: "Transit",
    category: "hot-jupiter",
    notableFact: "One of the largest, puffiest planets known; orbits retrograde (backwards relative to its star's spin).",
  },
  {
    name: "WASP-39 b",
    radiusEarth: 14.336,
    massEarth: 89.31,
    orbitalDistanceAU: 0.04828,
    orbitalPeriodDays: 4.0553,
    orbitalEccentricity: 0.0,
    equilibriumTemperatureK: 1166.0,
    starName: "WASP-39",
    starRadiusSolar: 0.939,
    starTemperatureK: 5485.0,
    starSpectralType: undefined,
    starMassSolar: 0.913,
    distanceLightYears: 697.92,
    discoveryYear: 2011,
    discoveryMethod: "Transit",
    category: "hot-jupiter",
    notableFact: "JWST early-release-science target — first clear exoplanet CO2 detection, a strong 'real recent science' talking point.",
  },
  {
    name: "HAT-P-11 b",
    radiusEarth: 4.36,
    massEarth: 25.0,
    orbitalDistanceAU: 0.05258,
    orbitalPeriodDays: 4.888,
    orbitalEccentricity: 0.251,
    equilibriumTemperatureK: 838.0,
    starName: "HAT-P-11",
    starRadiusSolar: 0.683,
    starTemperatureK: 4653.0,
    starSpectralType: "K4",
    starMassSolar: 0.811,
    distanceLightYears: 123.17,
    discoveryYear: 2010,
    discoveryMethod: "Transit",
    category: "mini-neptune",
    notableFact: "Neptune-size planet with confirmed water vapor in its atmosphere.",
  },
  {
    name: "Gliese 436 b",
    radiusEarth: 4.17,
    massEarth: 22.1,
    orbitalDistanceAU: 0.0291,
    orbitalPeriodDays: 2.6439,
    orbitalEccentricity: 0.1383,
    equilibriumTemperatureK: 686.0,
    starName: "Gliese 436",
    starRadiusSolar: 0.455,
    starTemperatureK: 3586.1,
    starSpectralType: "M2.5 V",
    starMassSolar: 0.47,
    distanceLightYears: 31.81,
    discoveryYear: 2004,
    discoveryMethod: "Radial Velocity",
    category: "mini-neptune",
    notableFact: "Hot Neptune shedding a comet-like tail of evaporating hydrogen.",
  },
  {
    name: "GJ 1214 b",
    radiusEarth: 2.733,
    massEarth: 8.41,
    orbitalDistanceAU: 0.01505,
    orbitalPeriodDays: 1.5804,
    orbitalEccentricity: 0.0062,
    equilibriumTemperatureK: 567.0,
    starName: "GJ 1214",
    starRadiusSolar: 0.2162,
    starTemperatureK: 3101.0,
    starSpectralType: "M4 V",
    starMassSolar: 0.182,
    distanceLightYears: 47.76,
    discoveryYear: 2009,
    discoveryMethod: "Transit",
    category: "mini-neptune",
    notableFact: "Archetypal 'water world' / mini-Neptune with a thick, hazy atmosphere obscuring surface studies.",
  },
  {
    name: "K2-18 b",
    radiusEarth: 2.37,
    massEarth: 8.92,
    orbitalDistanceAU: 0.1429,
    orbitalPeriodDays: 32.9396,
    orbitalEccentricity: 0.2,
    equilibriumTemperatureK: 284.0,
    starName: "K2-18",
    starRadiusSolar: 0.411,
    starTemperatureK: 3457.0,
    starSpectralType: "M2.5 V",
    starMassSolar: 0.359,
    distanceLightYears: 124.03,
    discoveryYear: 2015,
    discoveryMethod: "Transit",
    category: "mini-neptune",
    notableFact: "⚠️ Handle with care: widely (and prematurely) publicized 'biosignature' claims (DMS detection) remain scientifically contested — do not present as confirmed life indicators.",
  },
  {
    name: "WASP-107 b",
    radiusEarth: 10.48,
    massEarth: 33.022,
    orbitalDistanceAU: 0.055,
    orbitalPeriodDays: 5.7215,
    orbitalEccentricity: 0.052,
    equilibriumTemperatureK: 736.0,
    starName: "WASP-107",
    starRadiusSolar: 0.657,
    starTemperatureK: 4425.0,
    starSpectralType: "K6",
    starMassSolar: 0.683,
    distanceLightYears: 211.16,
    discoveryYear: 2017,
    discoveryMethod: "Transit",
    category: "mini-neptune",
    notableFact: "Extremely low-density 'super-puff' with detected helium actively escaping the atmosphere.",
  },
  {
    name: "HR 8799 c",
    radiusEarth: 13.0,
    massEarth: 3000.0,
    orbitalDistanceAU: 38.0,
    orbitalPeriodDays: 69000.0,
    orbitalEccentricity: 0.5,
    equilibriumTemperatureK: 1200.0,
    starName: "HR 8799",
    starRadiusSolar: 1.4934,
    starTemperatureK: 7204.6,
    starSpectralType: "A5 V",
    starMassSolar: 1.5,
    distanceLightYears: 134.52,
    discoveryYear: 2008,
    discoveryMethod: "Imaging",
    category: "directly-imaged",
    notableFact: "Part of one of the first directly-imaged multi-planet systems. Note: its archive equilibrium temperature (~1200K) reflects measured intrinsic/self-luminous heat from a still-forming young giant, not insolation — at 38 AU, starlight alone would leave it far colder.",
  },
  {
    name: "HR 8799 e",
    radiusEarth: 13.115,
    massEarth: 3178.3,
    orbitalDistanceAU: 16.4,
    orbitalPeriodDays: 20815.6,
    orbitalEccentricity: 0.15,
    equilibriumTemperatureK: 1150.0,
    starName: "HR 8799",
    starRadiusSolar: 1.4934,
    starTemperatureK: 7400.0,
    starSpectralType: "A5",
    starMassSolar: 1.51,
    distanceLightYears: 134.52,
    discoveryYear: 2010,
    discoveryMethod: "Imaging",
    category: "directly-imaged",
    notableFact: "Innermost known planet in the directly-imaged HR 8799 system. Same intrinsic-heat caveat as HR 8799 c applies to its ~1150K figure.",
  },
  {
    name: "Beta Pictoris b",
    radiusEarth: 18.495,
    massEarth: 2765.107,
    orbitalDistanceAU: 10.07,
    orbitalPeriodDays: 8682.0,
    orbitalEccentricity: 0.105,
    equilibriumTemperatureK: 1612.0,
    starName: "Beta Pictoris",
    starRadiusSolar: 1.5442,
    starTemperatureK: 8038.7,
    starSpectralType: "A6 V",
    starMassSolar: 1.789,
    distanceLightYears: 64.4,
    discoveryYear: 2008,
    discoveryMethod: "Imaging",
    category: "directly-imaged",
    notableFact: "Young, still-forming giant planet in a system with a visible debris disk. Archive name is 'bet Pic b' — note for future re-fetches.",
  },
  {
    name: "Kepler-16 b",
    radiusEarth: 8.449,
    massEarth: 105.833,
    orbitalDistanceAU: 0.7048,
    orbitalPeriodDays: 228.776,
    orbitalEccentricity: 0.0069,
    equilibriumTemperatureK: 205.9,
    starName: "Kepler-16 (AB)",
    starRadiusSolar: 0.6489,
    starTemperatureK: 4450.0,
    starSpectralType: undefined,
    starMassSolar: 0.6897,
    distanceLightYears: 244.9,
    discoveryYear: 2011,
    discoveryMethod: "Transit",
    category: "circumbinary",
    notableFact: "The original real-life 'Tatooine' — orbits two stars at once, would see a double sunset.",
  },
  {
    name: "TOI-1338 b",
    radiusEarth: 7.661,
    massEarth: 11.3,
    orbitalDistanceAU: 0.4607,
    orbitalPeriodDays: 95.4001,
    orbitalEccentricity: 0.0331,
    equilibriumTemperatureK: 254.7,
    starName: "TOI-1338 (AB)",
    starRadiusSolar: 1.313,
    starTemperatureK: 5723.2,
    starSpectralType: "F8",
    starMassSolar: 1.0936,
    distanceLightYears: 1301.43,
    discoveryYear: 2020,
    discoveryMethod: "Transit",
    category: "circumbinary",
    notableFact: "Circumbinary planet found by a 17-year-old NASA citizen-science intern reviewing TESS data.",
  },
  {
    name: "PSR B1257+12 b",
    radiusEarth: 0.338,
    massEarth: 0.02,
    orbitalDistanceAU: 0.19,
    orbitalPeriodDays: 25.262,
    orbitalEccentricity: 0.0,
    equilibriumTemperatureK: undefined,
    starName: "PSR B1257+12",
    starRadiusSolar: undefined,
    starTemperatureK: undefined,
    starSpectralType: undefined,
    starMassSolar: 1.4,
    distanceLightYears: 1956.96,
    discoveryYear: 1994,
    discoveryMethod: "Pulsar Timing",
    category: "pulsar-planet",
    notableFact: "Part of the first exoplanet system ever confirmed (1992) — orbits a millisecond pulsar. Star fields (temperature/radius/spectral type) are intentionally left blank: a pulsar isn't a normal blackbody star, so deriveEnvironment()'s Sun-like default is a deliberate simplification, not a data gap.",
  },
  {
    name: "PSR B1257+12 c",
    radiusEarth: 1.91,
    massEarth: 4.3,
    orbitalDistanceAU: 0.36,
    orbitalPeriodDays: 66.5419,
    orbitalEccentricity: 0.0186,
    equilibriumTemperatureK: undefined,
    starName: "PSR B1257+12",
    starRadiusSolar: undefined,
    starTemperatureK: undefined,
    starSpectralType: undefined,
    starMassSolar: 1.4,
    distanceLightYears: 1956.96,
    discoveryYear: 1992,
    discoveryMethod: "Pulsar Timing",
    category: "pulsar-planet",
    notableFact: "Sibling to PSR B1257+12 b; a genuinely alien host-star scenario (no visible starlight in the conventional sense). Same star-field caveat as PSR B1257+12 b applies.",
  },
  {
    name: "Kepler-11 f",
    radiusEarth: 2.49,
    massEarth: 2.0,
    orbitalDistanceAU: 0.25,
    orbitalPeriodDays: 46.6888,
    orbitalEccentricity: 0.013,
    equilibriumTemperatureK: 513.0,
    starName: "Kepler-11",
    starRadiusSolar: 1.065,
    starTemperatureK: 5663.0,
    starSpectralType: undefined,
    starMassSolar: 0.961,
    distanceLightYears: 2108.12,
    discoveryYear: 2010,
    discoveryMethod: "Transit",
    category: "oddity",
    notableFact: "Part of an extremely compact 6-planet system, all orbiting closer than Venus does to our Sun.",
  },
  {
    name: "Kepler-1625 b",
    radiusEarth: 6.06,
    massEarth: 30.6,
    orbitalDistanceAU: 0.87762,
    orbitalPeriodDays: 287.3789,
    orbitalEccentricity: 0.0,
    equilibriumTemperatureK: 350.0,
    starName: "Kepler-1625",
    starRadiusSolar: 0.94,
    starTemperatureK: 5677.0,
    starSpectralType: undefined,
    starMassSolar: 0.96,
    distanceLightYears: 7534.65,
    discoveryYear: 2016,
    discoveryMethod: "Transit",
    category: "oddity",
    notableFact: "⚠️ Handle with care: the planet itself is confirmed, but its candidate exomoon (Kepler-1625b-i) is disputed, not confirmed — don't present the moon as established fact.",
  },
  {
    name: "TOI-178 d",
    radiusEarth: 2.695,
    massEarth: 5.2,
    orbitalDistanceAU: 0.0592,
    orbitalPeriodDays: 6.5576,
    orbitalEccentricity: 0.0068,
    equilibriumTemperatureK: 690.0,
    starName: "TOI-178",
    starRadiusSolar: 0.662,
    starTemperatureK: 4316.0,
    starSpectralType: "K",
    starMassSolar: 0.647,
    distanceLightYears: 204.5,
    discoveryYear: 2021,
    discoveryMethod: "Transit",
    category: "oddity",
    notableFact: "Member of a 6-planet system locked in a rare, precise orbital resonance chain.",
  },
  {
    name: "TrES-2 b",
    radiusEarth: 15.244,
    massEarth: 473.567,
    orbitalDistanceAU: 0.03568,
    orbitalPeriodDays: 2.4706,
    orbitalEccentricity: 0.0,
    equilibriumTemperatureK: 1466.0,
    starName: "TrES-2",
    starRadiusSolar: 1.12,
    starTemperatureK: 5850.0,
    starSpectralType: "G0 V",
    starMassSolar: 1.36,
    distanceLightYears: 702.29,
    discoveryYear: 2006,
    discoveryMethod: "Transit",
    category: "oddity",
    notableFact: "Darkest known exoplanet — reflects less than 1% of incoming starlight, darker than coal.",
  },
  {
    name: "GJ 3512 b",
    radiusEarth: 14.3,
    massEarth: 146.519,
    orbitalDistanceAU: 0.3376,
    orbitalPeriodDays: 203.109,
    orbitalEccentricity: 0.4279,
    equilibriumTemperatureK: 97.2,
    starName: "GJ 3512",
    starRadiusSolar: 0.139,
    starTemperatureK: 3141.0,
    starSpectralType: "M5.5 V",
    starMassSolar: 0.123,
    distanceLightYears: 30.94,
    discoveryYear: 2019,
    discoveryMethod: "Radial Velocity",
    category: "oddity",
    notableFact: "Surprisingly massive gas giant around a tiny red dwarf — a system that strains standard planet-formation theory.",
  },
];

/** Quick lookup of how many buffer planets fall into each category. */
export function bufferCategoryCounts(): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const p of BUFFER_PLANETS) {
    const key = p.category ?? "uncategorized";
    counts[key] = (counts[key] ?? 0) + 1;
  }
  return counts;
}
